// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kjfjqtmtvxawmwjeedrd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtqZmpxdG10dnhhd213amVlZHJkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM0MTQyNzcsImV4cCI6MjA2ODk5MDI3N30.LtxrVqali42DKiivYiOgIEP1w7_ce1cyQzuQPYxuiCw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});